// This file is automatically generated by qtc from "home.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line web/home.qtpl:1
package web

//line web/home.qtpl:2
import "github.com/trashhalo/go-crud/db"

//line web/home.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line web/home.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line web/home.qtpl:4
func StreamHome(qw422016 *qt422016.Writer, todos []db.Todo) {
	//line web/home.qtpl:4
	qw422016.N().S(`
  <html>
    `)
	//line web/home.qtpl:6
	streamhead(qw422016)
	//line web/home.qtpl:6
	qw422016.N().S(`
    `)
	//line web/home.qtpl:7
	streambody(qw422016, todos)
	//line web/home.qtpl:7
	qw422016.N().S(`
  </html>
`)
//line web/home.qtpl:9
}

//line web/home.qtpl:9
func WriteHome(qq422016 qtio422016.Writer, todos []db.Todo) {
	//line web/home.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/home.qtpl:9
	StreamHome(qw422016, todos)
	//line web/home.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line web/home.qtpl:9
}

//line web/home.qtpl:9
func Home(todos []db.Todo) string {
	//line web/home.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/home.qtpl:9
	WriteHome(qb422016, todos)
	//line web/home.qtpl:9
	qs422016 := string(qb422016.B)
	//line web/home.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/home.qtpl:9
	return qs422016
//line web/home.qtpl:9
}

//line web/home.qtpl:11
func streamhead(qw422016 *qt422016.Writer) {
	//line web/home.qtpl:11
	qw422016.N().S(`
  <head>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bulma@0.7.1/css/bulma.min.css">
  </head>
`)
//line web/home.qtpl:15
}

//line web/home.qtpl:15
func writehead(qq422016 qtio422016.Writer) {
	//line web/home.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/home.qtpl:15
	streamhead(qw422016)
	//line web/home.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line web/home.qtpl:15
}

//line web/home.qtpl:15
func head() string {
	//line web/home.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/home.qtpl:15
	writehead(qb422016)
	//line web/home.qtpl:15
	qs422016 := string(qb422016.B)
	//line web/home.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/home.qtpl:15
	return qs422016
//line web/home.qtpl:15
}

//line web/home.qtpl:17
func streamform(qw422016 *qt422016.Writer) {
	//line web/home.qtpl:17
	qw422016.N().S(`
  <form action="/todo" method="POST">
    <div class="field has-addons">
      <div class="control is-expanded">
        <input class="input" name="todo" type="text">
      </div>
      <div class="control">
        <input class="button is-primary" type="submit" value="todo">
      </div>
  </form>
`)
//line web/home.qtpl:27
}

//line web/home.qtpl:27
func writeform(qq422016 qtio422016.Writer) {
	//line web/home.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/home.qtpl:27
	streamform(qw422016)
	//line web/home.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line web/home.qtpl:27
}

//line web/home.qtpl:27
func form() string {
	//line web/home.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/home.qtpl:27
	writeform(qb422016)
	//line web/home.qtpl:27
	qs422016 := string(qb422016.B)
	//line web/home.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/home.qtpl:27
	return qs422016
//line web/home.qtpl:27
}

//line web/home.qtpl:29
func streamlist(qw422016 *qt422016.Writer, todos []db.Todo) {
	//line web/home.qtpl:29
	qw422016.N().S(`
  `)
	//line web/home.qtpl:30
	for _, todo := range todos {
		//line web/home.qtpl:30
		qw422016.N().S(`
    `)
		//line web/home.qtpl:31
		if !todo.Done {
			//line web/home.qtpl:31
			qw422016.N().S(`
    <nav class="box level">
      <div class="level-left">
        <div class="level-item">
          <form action="/todo/`)
			//line web/home.qtpl:35
			qw422016.E().S(todo.Key)
			//line web/home.qtpl:35
			qw422016.N().S(`" method="POST" class="is-marginless"> 
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" name="done" value="true">
            <input type="submit" class="button" value="done">
          </form>
        </div>
        <div class="level-item"> `)
			//line web/home.qtpl:41
			qw422016.E().S(todo.Text)
			//line web/home.qtpl:41
			qw422016.N().S(` </div>
      </div>
    </nav>
    `)
			//line web/home.qtpl:44
		}
		//line web/home.qtpl:44
		qw422016.N().S(`
  `)
		//line web/home.qtpl:45
	}
	//line web/home.qtpl:45
	qw422016.N().S(`
`)
//line web/home.qtpl:46
}

//line web/home.qtpl:46
func writelist(qq422016 qtio422016.Writer, todos []db.Todo) {
	//line web/home.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/home.qtpl:46
	streamlist(qw422016, todos)
	//line web/home.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line web/home.qtpl:46
}

//line web/home.qtpl:46
func list(todos []db.Todo) string {
	//line web/home.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/home.qtpl:46
	writelist(qb422016, todos)
	//line web/home.qtpl:46
	qs422016 := string(qb422016.B)
	//line web/home.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/home.qtpl:46
	return qs422016
//line web/home.qtpl:46
}

//line web/home.qtpl:48
func streambody(qw422016 *qt422016.Writer, todos []db.Todo) {
	//line web/home.qtpl:48
	qw422016.N().S(`
  <body>
    <section class="section">
      <div class="container">
        `)
	//line web/home.qtpl:52
	streamlist(qw422016, todos)
	//line web/home.qtpl:52
	qw422016.N().S(`        
        `)
	//line web/home.qtpl:53
	streamform(qw422016)
	//line web/home.qtpl:53
	qw422016.N().S(`        
      </div>
    </section>
  </body>
`)
//line web/home.qtpl:57
}

//line web/home.qtpl:57
func writebody(qq422016 qtio422016.Writer, todos []db.Todo) {
	//line web/home.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line web/home.qtpl:57
	streambody(qw422016, todos)
	//line web/home.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line web/home.qtpl:57
}

//line web/home.qtpl:57
func body(todos []db.Todo) string {
	//line web/home.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
	//line web/home.qtpl:57
	writebody(qb422016, todos)
	//line web/home.qtpl:57
	qs422016 := string(qb422016.B)
	//line web/home.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
	//line web/home.qtpl:57
	return qs422016
//line web/home.qtpl:57
}
